version: "2"
services:
  eros-publish:
    image: eros-publish
    container_name: eros-publish
    restart: always
    build: .
    
    depends_on:
      - mongo
    ports:
      - 3008:3001
    volumes:
      - ./static:/root/Service/static
  mongo:
    image: mongo
    container_name: eros-publish-mongo
    restart: always
    volumes:
      - ./datadir:/data/db
    